language: cpp

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.9.0


matrix:
  fast_finish: true
  include:
# linux + gcc

    - os: linux
      compiler: gcc
      name: ubuntu 14.04 - gcc@5.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - COMPILER_ID="gcc"

    - os: linux
      compiler: gcc
      name: ubuntu 14.04 - gcc@6.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - COMPILER_ID="gcc"

    - os: linux
      compiler: gcc
      name: ubuntu 14.04 - gcc@7.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - python3.4
            - python3.4-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - COMPILER_ID="gcc"

    - os: linux
      compiler: gcc
      name: ubuntu 14.04 - gcc@8.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - python3.5
            - python3.5-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - COMPILER_ID="gcc"

# linux + clang



    - os: linux
      compiler: clang
      name: ubuntu 14.04 - clang@3.9
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libstdc++-7-dev
            - libclang-3.9-dev
            - libc++abi-dev
            - libc++-dev
            - llvm-4.0-dev
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
        - LINKER_FLAGS="-stdlib=libc++ -lc++abi"
        - COMPILER_ID="clang"

    - os: linux
      compiler: clang
      name: ubuntu 14.04 - clang@4.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libstdc++-7-dev
            - libclang-4.0-dev
            - libc++abi-dev
            - libc++-dev
            - llvm-4.0-dev

      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
        - LINKER_FLAGS="-stdlib=libc++ -lc++abi"
        - COMPILER_ID="clang"

    - os: linux
      compiler: clang
      name: ubuntu 14.04 - clang@5.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libstdc++-7-dev
            - libclang-5.0-dev

      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - LINKER_FLAGS="-stdlib=libc++ -lc++abi"
        - COMPILER_ID="clang"

    - os: linux
      compiler: clang
      name: ubuntu 14.04 - clang@6.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - clang-6.0
            - libstdc++-7-dev
            - libclang-6.0-dev

      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
        - LINKER_FLAGS="-stdlib=libc++ -lc++abi"
        - COMPILER_ID="clang"

    - os: linux
      compiler: clang
      name: ubuntu 14.04 - clang@7.0
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-trusty-7
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - clang-7
            - libstdc++6-4.6-dev
            - libclang-7-dev
            - llvm-7-dev
            - libc++-dev
            - libc++abi-dev

      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
        - LINKER_FLAGS="-stdlib=libc++ -lc++abi"
        - COMPILER_ID="clang"

# osx + gcc

    - os: osx
      osx_image: xcode10.1
      compiler: gcc
      name: macOS - g++-7
      env:
        - MATRIX_EVAL="brew update && brew install gcc@7 gcc && CC=gcc-7 && CXX=g++-7"
        - COMPILER_ID="gcc"

    - os: osx
      osx_image: xcode10.1
      compiler: gcc
      name: macOS - g++-8
      env:
        - MATRIX_EVAL="brew update && brew install gcc@8 gcc && CC=gcc-8 && CXX=g++-8"
        - COMPILER_ID="gcc"

# osx + clang
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      name: macOS - native clang (llvm backend)
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
          packages:
            - libc++-dev
            - libc++abi-dev
      env:
        - MATRIX_EVAL=""
        - LINKER_FLAGS="-stdlib=libc++ -lc++abi"
        - COMPILER_ID="clang"

    - os: osx
      osx_image: xcode10.1
      compiler: clang
      name: macOS - clang@7.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7.0
            - python3.6
            - python3.6-dev
      env:
        - MATRIX_EVAL="brew update && brew install llvm && CC=clang-7 && CXX=clang++-7"
        - LINKER_FLAGS="-stdlib=libc++ -lc++abi"
        - COMPILER_ID="clang"

  allow_failures:
    - name: ubuntu 14.04 - gcc@5.0 # not support the full std=c++17
    - name: ubuntu 14.04 - gcc@6.0 # not support the full std=c++17
    - name: ubuntu 14.04 - clang@3.9
    - name: ubuntu 14.04 - clang@4.0
    - name: ubuntu 14.04 - clang@7.0
    - name: macOS - native clang (llvm backend)
    - name: macOS - clang@7.0


before_install:
  - travis_retry eval "${MATRIX_EVAL}"
  - pip install --user codecov
  - sudo pip install -r requirements.txt

install:
  # CMake upgrade

  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.1-Darwin-x86_64.tar.gz   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then tar -xzf cmake-3.13.1-Darwin-x86_64.tar.gz                                                    ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export PATH=$PWD/cmake-3.13.1-Darwin-x86_64/CMake.app/Contents/bin:$PATH                      ;fi

  ###############################################################################################################################################

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$COMPILER_ID" == "gcc" ]]; then wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.tar.gz    ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$COMPILER_ID" == "gcc" ]]; then tar -xzf cmake-3.13.1-Linux-x86_64.tar.gz                                                     ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$COMPILER_ID" == "gcc" ]]; then export PATH=$PWD/cmake-3.13.1-Linux-x86_64/bin:$PATH                                          ;fi

script:
  - chmod 777 ./build.sh
  - if [[ "$COMPILER_ID" == "clang" ]]; then bash ./build.sh "" OFF                                                                           ;fi
  - if [[ "$COMPILER_ID" == "gcc"   ]]; then bash ./build.sh "" ON                                                                            ;fi
